const COPY = {
  en: {
    romantic: {
      question: '{name}, will you be my date? 🥺',
      yes: 'Yes, I will! 💖',
      no: 'Not this time',
      planTitle: 'Let’s plan something special 😍',
      planSummary: 'Here is what was planned for you:',
      dateLabel: 'Which day works for you?',
      timeLabel: 'What time works for you?',
      submit: 'Make it official! 💃',
      successTitle: 'It’s a date! ❤️',
      successText: 'I can’t wait to see you! 😘',
      declineTitle: 'No worries 💛',
      declineText: 'Thanks for being honest. The invitation will always be here if you change your mind.',
      footer: 'A little invitation made with a lot of heart.',
      noMessages: ['Are you sure?', 'Take your time', 'No pressure at all'],
    },
    playful: {
      question: '{name}, ready for a little adventure with me? ✨',
      yes: 'Let’s go! 💖',
      no: 'Maybe later',
      planTitle: 'Oya, let’s plan this adventure! 😍',
      planSummary: 'The important details:',
      dateLabel: 'Pick a day',
      timeLabel: 'Pick a time',
      submit: 'Lock it in! 🚀',
      successTitle: 'We have a date! 🎉',
      successText: 'This is going to be so much fun! 😘',
      declineTitle: 'No wahala 💛',
      declineText: 'Thanks for being honest. No hard feelings.',
      footer: 'Normal messages are easy. This one took a whole website. 😉',
      noMessages: ['No wahala', 'Think am well', 'Last chance to smile'],
    },
    simple: {
      question: '{name}, would you like to go on a date with me?',
      yes: 'Yes, I would 💖',
      no: 'No, thank you',
      planTitle: 'Choose a date and time',
      planSummary: 'Invitation details:',
      dateLabel: 'Date',
      timeLabel: 'Time',
      submit: 'Confirm date',
      successTitle: 'Date confirmed ❤️',
      successText: 'Looking forward to seeing you.',
      declineTitle: 'Thank you for letting me know',
      declineText: 'No hard feelings. I wish you all the best.',
      footer: 'Made with care.',
      noMessages: ['No, thank you', 'Maybe another time', 'I understand'],
    },
  },
  pidgin: {
    romantic: {
      question: '{name}, you go be my date? 🥺',
      yes: 'Yes, I go! 💖',
      no: 'No be today',
      planTitle: 'Oya, make we plan something special 😍',
      planSummary: 'See wetin we get planned:',
      dateLabel: 'Which day go work for you?',
      timeLabel: 'What time go work for you?',
      submit: 'Make am official! 💃',
      successTitle: 'Na date! ❤️',
      successText: 'I no fit wait to see you! 😘',
      declineTitle: 'No wahala 💛',
      declineText: 'Thanks for being honest. No hard feelings at all.',
      footer: 'Small invitation, plenty love.',
      noMessages: ['You sure?', 'Take your time', 'No pressure o'],
    },
    playful: {
      question: '{name}, you ready for small adventure with me? ✨',
      yes: 'Oya, let’s go! 💖',
      no: 'Maybe later',
      planTitle: 'Oya, make we plan this adventure! 😍',
      planSummary: 'The important gist:',
      dateLabel: 'Pick a day',
      timeLabel: 'Pick a time',
      submit: 'Lock am in! 🚀',
      successTitle: 'We get date! 🎉',
      successText: 'This one go sweet well well! 😘',
      declineTitle: 'No wahala 💛',
      declineText: 'Thanks for being honest. No vex.',
      footer: 'Normal guys send text, I build website. 😉',
      noMessages: ['No wahala', 'Think am well', 'Smile first'],
    },
    simple: {
      question: '{name}, you go like go on date with me?',
      yes: 'Yes, I go 💖',
      no: 'No, thank you',
      planTitle: 'Choose day and time',
      planSummary: 'Invitation details:',
      dateLabel: 'Day',
      timeLabel: 'Time',
      submit: 'Confirm date',
      successTitle: 'Date confirmed ❤️',
      successText: 'I dey look forward to seeing you.',
      declineTitle: 'Thanks for telling me',
      declineText: 'No vex. I wish you all the best.',
      footer: 'Made with care.',
      noMessages: ['No, thank you', 'Maybe another time', 'I understand'],
    },
  },
};

export function getInvitationCopy(locale = 'en', tone = 'romantic', name = 'there') {
  const language = COPY[locale] || COPY.en;
  const selected = language[tone] || language.romantic;
  return {
    ...selected,
    question: selected.question.replace('{name}', name || 'there'),
  };
}
